### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/autobot#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Dashboard creation

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

3 buttons

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="389" alt="Screenshot 2023-10-02 at 12 50 57 AM" src="https://github.com/Lambpato/autobot/assets/34325124/da167d1c-a2fc-4b7a-a88e-5036ec439188">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

Run 

chrome.runtime.sendMessage({ message: 'Hello from Angular' }, (response) => {
  console.log(response);
});

On top of components to check communication between Angular components and background script.

- [ ] Create Angular App with TypeScript
- [ ] Install Tailwind
- [ ] Create a manifest.json file
- [ ] Create a background.js file
   - [ ] Track state of current tab
- [ ] Build Angular App
- [ ] Load Extension by opening the Chrome, go to chrome://extensions/, enable "Developer mode," and click "Load unpacked." Select the folder where Angular was built on
- [ ] Create Header Component  
- [ ] Create 3 Buttons Each Routing to The Corresponding Page

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all tailwind properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
